### ISSUE TITLE
ContextAwareRepository StackOverflowError when adding model

### ISSUE THREAD

**Issue by domkun** [eclipse-rdf4j/rdf4j#4826]
### Current Behavior

Using the `ContextAwareRepository` and calling `connection.add(model)` results in a `StackOverflowError` in 

```
at org.eclipse.rdf4j.repository.RepositoryConnection.add(RepositoryConnection.java:988)
at org.eclipse.rdf4j.repository.contextaware.ContextAwareConnection.add(ContextAwareConnection.java:330)
```

### Expected Behavior

Model gets added to repository.

### Steps To Reproduce

To reproduce use the following code:

```
import org.eclipse.rdf4j.model.Model;
import org.eclipse.rdf4j.model.impl.DynamicModelFactory;
import org.eclipse.rdf4j.model.util.Values;
import org.eclipse.rdf4j.repository.Repository;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.contextaware.ContextAwareRepository;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.sail.memory.MemoryStore;

class Scratch {
    public static void main(String[] args) {
        ContextAwareRepository ctxAwareRepo = new ContextAwareRepository(new SailRepository(new MemoryStore()));
        ctxAwareRepo.setInsertContext(Values.iri("some:default"));
        ctxAwareRepo.setReadContexts(Values.iri("some:default"));

        works(ctxAwareRepo);
        fails(ctxAwareRepo);
    }

    public static void fails(Repository repo) {
        try (RepositoryConnection conn = repo.getConnection()) {
            Model model = new DynamicModelFactory().createEmptyModel();
            model.add(Values.iri("some:iri"), Values.iri("some:p"), Values.literal("some"));
            conn.add(model);
            conn.getStatements(null, null, null).forEach(System.out::println);
        }
    }

    public static void works(Repository repo) {
        try (RepositoryConnection conn = repo.getConnection()) {
            conn.add(Values.iri("some:iri"), Values.iri("some:p"), Values.literal("some"));
            conn.getStatements(null, null, null).forEach(System.out::println);
        }
    }
}
```

### Version

4.3.7

### Are you interested in contributing a solution yourself?

None

**Comment by domkun** [comment]
I think the problem is located here: https://github.com/eclipse-rdf4j/rdf4j/blob/743673ba3db331fa07e2b7360153adbd1d88db8c/core/repository/contextaware/src/main/java/org/eclipse/rdf4j/repository/contextaware/ContextAwareConnection.java#L330

Casting the `ConvertingIteration` to `Iteration<? extends Statement, E>` fixes the problem, however I currently struggle to write a sane test for this. I added a PR anyways, maybe it helps.
